<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>disable</Nullable>
		<UserSecretsId>b90020bc-a4e3-48f5-aeb7-33b372226dac</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<CopyToPublishDirectory>Always</CopyToPublishDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="7.0.3" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="7.0.0" />
		<PackageReference Include="MongoDB.Driver" Version="2.19.0" />
	</ItemGroup>

	<ItemGroup>
		<DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="2.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Models\Models.csproj" />
	  <ProjectReference Include="..\Shared\Shared.csproj" />
	</ItemGroup>

</Project>
