// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Models.Entities.Component", b =>
                {
                    b.Property<int>("ParentElementId")
                        .HasColumnType("int");

                    b.Property<int>("ChildElementId")
                        .HasColumnType("int");

                    b.Property<double>("Ratio")
                        .HasColumnType("float");

                    b.HasKey("ParentElementId", "ChildElementId");

                    b.HasIndex("ChildElementId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("Models.Entities.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GTIN")
                        .HasColumnType("int");

                    b.Property<string>("GlobalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("Models.Entities.Element2Tag", b =>
                {
                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ElementId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("Element2Tags");
                });

            modelBuilder.Entity("Models.Entities.Household", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Households");
                });

            modelBuilder.Entity("Models.Entities.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<int?>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("ValueListType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("Properties", (string)null);
                });

            modelBuilder.Entity("Models.Entities.PropertyValue", b =>
                {
                    b.Property<int>("PropertyId")
                        .HasColumnType("int");

                    b.Property<bool?>("Bool")
                        .HasColumnType("bit");

                    b.Property<string>("String")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double?>("Double")
                        .HasColumnType("float");

                    b.Property<int?>("Int")
                        .HasColumnType("int");

                    b.Property<int?>("Element2TagElementId")
                        .HasColumnType("int");

                    b.Property<int?>("Element2TagTagId")
                        .HasColumnType("int");

                    b.Property<int?>("Tag2TagChildTagId")
                        .HasColumnType("int");

                    b.Property<int?>("Tag2TagParentTagId")
                        .HasColumnType("int");

                    b.HasKey("PropertyId", "Bool", "String", "Double", "Int");

                    b.HasIndex("Element2TagElementId", "Element2TagTagId");

                    b.HasIndex("Tag2TagParentTagId", "Tag2TagChildTagId");

                    b.ToTable("PropertyValues");
                });

            modelBuilder.Entity("Models.Entities.Shop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("Models.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ElementId")
                        .HasColumnType("int");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int?>("ShopId")
                        .HasColumnType("int");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ValidTill")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ElementId");

                    b.HasIndex("HouseholdId");

                    b.HasIndex("ShopId");

                    b.HasIndex("StoreId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Models.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShopId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Models.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Models.Entities.Tag2Tag", b =>
                {
                    b.Property<int>("ParentTagId")
                        .HasColumnType("int");

                    b.Property<int>("ChildTagId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ParentTagId", "ChildTagId");

                    b.HasIndex("ChildTagId");

                    b.ToTable("Tag2Tags");
                });

            modelBuilder.Entity("Models.Entities.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ActivateLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Activated")
                        .HasColumnType("bit");

                    b.Property<int>("AuthType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HouseHoldId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserPermission")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HouseHoldId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Models.Entities.Component", b =>
                {
                    b.HasOne("Models.Entities.Element", "ChildElement")
                        .WithMany("ParentComponents")
                        .HasForeignKey("ChildElementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Element", "ParentElement")
                        .WithMany("Components")
                        .HasForeignKey("ParentElementId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChildElement");

                    b.Navigation("ParentElement");
                });

            modelBuilder.Entity("Models.Entities.Element2Tag", b =>
                {
                    b.HasOne("Models.Entities.Element", "Element")
                        .WithMany("Element2Tags")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.Tag", "Tag")
                        .WithMany("Element2Tags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Models.Entities.Property", b =>
                {
                    b.HasOne("Models.Entities.Tag", null)
                        .WithMany("Properties")
                        .HasForeignKey("TagId");
                });

            modelBuilder.Entity("Models.Entities.PropertyValue", b =>
                {
                    b.HasOne("Models.Entities.Property", "Property")
                        .WithMany("PropertyValues")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.Element2Tag", null)
                        .WithMany("PropertyValues")
                        .HasForeignKey("Element2TagElementId", "Element2TagTagId");

                    b.HasOne("Models.Entities.Tag2Tag", null)
                        .WithMany("PropertyValues")
                        .HasForeignKey("Tag2TagParentTagId", "Tag2TagChildTagId");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("Models.Entities.Stock", b =>
                {
                    b.HasOne("Models.Entities.Element", "Element")
                        .WithMany("Stocks")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.Household", "Household")
                        .WithMany("Stocks")
                        .HasForeignKey("HouseholdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Entities.Shop", null)
                        .WithMany("Stocks")
                        .HasForeignKey("ShopId");

                    b.HasOne("Models.Entities.Store", null)
                        .WithMany("Stocks")
                        .HasForeignKey("StoreId");

                    b.Navigation("Element");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Models.Entities.Store", b =>
                {
                    b.HasOne("Models.Entities.Tag", "ChildTag")
                        .WithMany("Stores")
                        .HasForeignKey("ShopId");
                });

            modelBuilder.Entity("Models.Entities.Tag2Tag", b =>
                {
                    b.HasOne("Models.Entities.Tag", "ChildTag")
                        .WithMany("ParentTag2Tags")
                        .HasForeignKey("ChildTagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Models.Entities.Tag", "ParentTag")
                        .WithMany("Tag2Tags")
                        .HasForeignKey("ParentTagId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChildTag");

                    b.Navigation("ParentTag");
                });

            modelBuilder.Entity("Models.Entities.Element", b =>
                {
                    b.HasOne("Models.Entities.Household", "Household")
                        .WithMany()
                        .HasForeignKey("HouseHoldId");

                    b.Navigation("Household");
                });

            modelBuilder.Entity("Models.Entities.Element", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("Element2Tags");

                    b.Navigation("ParentComponents");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Models.Entities.Element2Tag", b =>
                {
                    b.Navigation("PropertyValues");
                });

            modelBuilder.Entity("Models.Entities.Household", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Models.Entities.Property", b =>
                {
                    b.Navigation("PropertyValues");
                });

            modelBuilder.Entity("Models.Entities.Shop", b =>
                {
                    b.Navigation("Stocks");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("Models.Entities.Store", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("Models.Entities.Tag", b =>
                {
                    b.Navigation("Element2Tags");

                    b.Navigation("ParentTag2Tags");

                    b.Navigation("Properties");

                    b.Navigation("Tag2Tags");
                });

            modelBuilder.Entity("Models.Entities.Tag2Tag", b =>
                {
                    b.Navigation("PropertyValues");
                });
#pragma warning restore 612, 618
        }
    }
}
