import type { AppRoute } from "../../app-route-context.js";
import {
  acceptHouseholdInvitationRoute,
  householdInvitationsRoute,
  pendingHouseholdInvitationsRoute
} from "../household-invitation-routes.js";
import {
  householdShoppingListPreviewRoute,
  householdShoppingListsRoute,
  householdShoppingListUpdateStocksRoute,
  householdSettingsRoute,
  householdStockRoute,
  householdsRoute,
  latestHouseholdShoppingListRoute,
  shopsRoute
} from "../household-routes.js";
import {
  householdV2AllocateBatchRoute,
  householdV2ConsumeRoute,
  householdV2CorrectBatchRoute,
  householdV2DiscardBatchRoute,
  householdV2HouseholdConceptsRoute,
  householdV2HouseholdProductClassificationRoute,
  householdV2HouseholdProductCollectionRoute,
  householdV2HouseholdProductIdentityRoute,
  householdV2ManualBatchRoute,
  householdV2ProductComposerRoute,
  householdV2ProductGroupCollectionRoute,
  householdV2ProductGroupMutationRoute,
  householdV2ShopMarketsRoute,
  householdV2ShoppingNeedTransitionRoute,
  householdV2ShoppingNeedsRoute,
  householdV2ShoppingTripCompleteRoute,
  householdV2ShoppingTripRoute,
  householdV2ShoppingTripsRoute,
  householdV2StockTargetCollectionRoute,
  householdV2StockTargetMutationRoute,
  householdV2StockTargetRoute,
  householdV2WorkspaceRoute
} from "../household-v2-routes.js";

export const householdRoutes: AppRoute[] = [
  householdInvitationsRoute,
  pendingHouseholdInvitationsRoute,
  acceptHouseholdInvitationRoute,
  householdsRoute,
  householdStockRoute,
  householdSettingsRoute,
  householdV2StockTargetRoute,
  householdV2StockTargetCollectionRoute,
  householdV2StockTargetMutationRoute,
  householdV2HouseholdProductCollectionRoute,
  householdV2HouseholdConceptsRoute,
  householdV2HouseholdProductClassificationRoute,
  householdV2HouseholdProductIdentityRoute,
  householdV2ProductGroupCollectionRoute,
  householdV2ProductGroupMutationRoute,
  householdV2ProductComposerRoute,
  householdV2WorkspaceRoute,
  householdV2ShopMarketsRoute,
  householdV2ManualBatchRoute,
  householdV2AllocateBatchRoute,
  householdV2ConsumeRoute,
  householdV2CorrectBatchRoute,
  householdV2DiscardBatchRoute,
  householdV2ShoppingNeedsRoute,
  householdV2ShoppingTripCompleteRoute,
  householdV2ShoppingTripsRoute,
  householdV2ShoppingTripRoute,
  householdV2ShoppingNeedTransitionRoute,
  householdShoppingListPreviewRoute,
  householdShoppingListsRoute,
  latestHouseholdShoppingListRoute,
  householdShoppingListUpdateStocksRoute,
  shopsRoute
];
