<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack.CssSelectors.NetCore" Version="1.2.1" />
    <PackageReference Include="Microsoft.Playwright" Version="1.31.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\KamraBE\Shared\Shared.csproj" />
    <ProjectReference Include="..\MongoDbConnector\MongoDbConnector.csproj" />
  </ItemGroup>

</Project>
