# workflow auto-pr
workflow "auto-pr" {
  resolves = ["create-pr"]
  on = "push"
}

action "create-pr" {
  uses = "smartinspereira/auto-create-pr-action@master"
  secrets = ["GITHUB_TOKEN"]
  env = {
    BRANCH_PREFIX = "slave"
    # BASE_BRANCH = "master"
    # PULL_REQUEST_TITLE = "New Request"
    # PULL_REQUEST_BODY = "Please check it out if you can"
    # PULL_REQUEST_DRAFT = "true"
  }
}
